### ISSUE TITLE
References are not realized

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/raml-dt-schema-parser#26]
#### Describe the bug
With the test case given the property [proscons of cat](https://github.com/asyncapi/raml-dt-schema-parser/blob/2a0658c4c33948ed6254158bea02f47420b62e21/test/complex_cat.raml#L69) is rendered as 
```
"anyOf": [
    true,
    true
],
```
Where I would expect the anyOf array to contain the actual schemas of the two being referenced.

Same goes for `name`, `breed` and `age` of cat.

**Comment by derberg** [comment]
@jonaslagoni is this one still valid? I guess it is, but it is something that has to be fixed in the dependant library right?

**Comment by jonaslagoni** [comment]
> @jonaslagoni is this one still valid? I guess it is, but it is something that has to be fixed in the dependant library right?

Have not checked since, but I would assume so yes.

Related issue https://github.com/raml-org/ramldt2jsonschema/issues/124
